# Generated by Django 5.0 on 2024-12-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at_post_updated_at_alter_post_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='UserPostInteraction',
        ),
    ]
