# Generated by Django 5.0 on 2024-12-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_author_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
